[tool.poetry]
name = "Sistema de gestion de viajes"
version = "0.1.0"
description = "App web con FastAPI, MySQL y Bootstrap"
authors = ["Benjamín Peralta", "Fernando Colazo", "German Sosa", "Juan Rusconi"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.13.*"
fastapi = "0.115.13"
uvicorn = "0.34.3"
sqlalchemy = "2.0.41"
mysql-connector-python = "9.3.0"
<<<<<<< HEAD
passlib = "1.7.4"
python-multipart = "0.0.20"
python-dotenv = "1.1.1"
pyjwt = "2.10.1"
python-dotenv = "1.1.1"
=======
>>>>>>> 00142904fbea67cc287c098406e1b8678ca124cf

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
